name: TFT Match Checker

on:
  repository_dispatch:
    types: [run-tft-check]
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-bot:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run bot
        env:
          RIOT_API_KEY: ${{ secrets.RIOT_API_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          RIOT_ID: ${{ secrets.RIOT_ID }}
          NAME: ${{ secrets.NAME }}
        run: python bot.py

      - name: Commit prev.txt if changed
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add prev.txt

          if ! git diff --cached --quiet; then
            git commit -m "Update last match"
            git push
          else
            echo "No changes to commit"
          fi
